//JSON data
module.exports = {
  organization_id: {
    organization_username: "hudson_hifi",
    company_name: "HUDSON HI-FI INC",
    theme: "dark",
    mode: "slim",
    city: "4324 ST PETERSBURG",
    state: "FL",
    country: "USA",
    zip_code: "33702",
    address: "7901 4TH ST N STE",
    phone: "1.845.323.2212",
    ATTN: "ELY LIBEROV",
    PI: "V-25032021",
  },
  vendor_id: {
    organization_id: "123456789",
    vendor_name: "ARRIVAL TECHNOLOGY (XIAMEN) CO., LTD",
    lead_time: "",
    email: "",
    phone: "(86) 592 2912 640",
    mobile: "(86) 18950000813",
    address: {
      address_line_one: "5/F BLDG 1 NO. 2 XIAYANG RD",
      address_line_two: "",
    },
    city: "XIAMEN",
    state: "HAICANG",
    country: "CHINA",
    zip_code: "",
  },
  fulfillment_provider_id: {
    marketplace_region_id: "789456123",
    organization_id: "123456789",
    name: "",
    type: "",
    integration_type: "",
  },
  status: "open",
  items: [
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "ACRYLIC MAT RED",
        p_sku: "",
        p_title: "ACRYLIC_SLIPMAT_LIT_RED_M",
        p_price: 4.15,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 3 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 195,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "ACRYLIC MAT YELLOW",
        p_sku: "",
        p_title: "ACRYLIC_SLIPMAT_LIT_YELLOW_M",
        p_price: 4.15,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 4 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 260,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "ACRYLIC MAT GREEN",
        p_sku: "",
        p_title: "ACRYLIC_SLIPMAT_LIT_GREEN_M",
        p_price: 4.15,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 9 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 585,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "ACRYLIC MAT BLUE",
        p_sku: "",
        p_title: "ACRYLIC_SLIPMAT_LIT_BLUE_M",
        p_price: 4.15,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 3 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 195,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "ACRYLIC MAT ORANGE",
        p_sku: "",
        p_title: "ACRYLIC_SLIPMAT_LIT_ORANGE_M",
        p_price: 4.15,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 3 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 195,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "ACRYLIC MAT WHITE",
        p_sku: "",
        p_title: "ACRYLIC_SLIPMAT_SOLID_WHITE_M",
        p_price: 4.15,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 3 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 195,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "ACRYLIC MAT BLACK",
        p_sku: "",
        p_title: "ACRYLIC_SLIPMAT_SOLID_BLACK_M",
        p_price: 4.15,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 3 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 195,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "ACRYLIC MAT TRANSPARENT",
        p_sku: "",
        p_title: "ACRYLIC_SLIPMAT_SOLID_TRANSPARENT_M",
        p_price: 4.15,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 16 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 1040,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "STROBO_MAT_M",
        p_price: 4.18,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 5 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 325,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "PS_CARTRIDGE_ALIGNMENT_MAT_M",
        p_price: 4.18,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 4 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 260,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "DOUBLESIDED_PROTOMAT2_M",
        p_price: 5.43,
        p_currency: "USD",
        p_description: "65 PCS PER CARTON, 4 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 260,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "PROTRACTOR_HIGH CONTRAST_M",
        p_price: 0.81,
        p_currency: "USD",
        p_description: "150 PCS PER CARTON, 2 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 300,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "PROTRACTOR_MIRRORED_M",
        p_price: 0.88,
        p_currency: "USD",
        p_description: "150 PCS PER CARTON, 1 CARTON",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 150,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "25LP_WALL_MOUNT_BLACK_SINGLE_M",
        p_price: 7.07,
        p_currency: "USD",
        p_description: "59 CARTONS, 9 PCS PER CARTON",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 531,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "25LP_WALL_MOUNT_BLACK_2PK_M",
        p_price: 13.86,
        p_currency: "USD",
        p_description: "52 CARTONS, 9 PCS PER CARTON",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 468,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "25LP_WALL_MOUNT_WHITE_SINGLE_M",
        p_price: 7.07,
        p_currency: "USD",
        p_description: "83 CARTONS, 9 PCS PER CARTON",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 747,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "25LP_WALL_MOUNT_WHITE_2PK_M",
        p_price: 13.86,
        p_currency: "USD",
        p_description: "44 CARTONS, 9 PCS PER CARTON",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 396,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_BLACK_4PK_NEW",
        p_price: 4.0,
        p_currency: "USD",
        p_description: "22 CARTONS, 18 UNITS/CARTON, 4 PCS/UNIT",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 396,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_BLACK_6PK_M",
        p_price: 6.0,
        p_currency: "USD",
        p_description: "32 CARTONS, 12 UNITS/CARTON, 6 PCS/UNIT",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 384,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_BLACK_12PK_M",
        p_price: 12.0,
        p_currency: "USD",
        p_description: "66 CARTONS, 6 UNITS/CARTON, 12 PCS/UNIT",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 396,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_BLACK_SINGLE_M",
        p_price: 1.0,
        p_currency: "USD",
        p_description: "40 PCS PER CARTON, 11 CARTONS",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 440,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_GREY_4PK_M",
        p_price: 4.0,
        p_currency: "USD",
        p_description: "20 CARTONS, 18 UNITS/CARTON, 4 PCS/UNIT",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 360,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_GREY_6PK_M",
        p_price: 6.0,
        p_currency: "USD",
        p_description: "32 CARTONS, 12 UNITS/CARTON, 6 PCS/UNIT",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 384,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_WHITE_4PK_M",
        p_price: 4.0,
        p_currency: "USD",
        p_description: "21 CARTONS, 18 UNITS/CARTON, 4 PCS/UNIT",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 378,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_WHITE_6PK_M",
        p_price: 6.0,
        p_currency: "USD",
        p_description: "32 CARTONS, 12 UNITS/CARTON, 6 PCS/UNIT",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 384,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_CLEAR_4PK",
        p_price: 3.93,
        p_currency: "USD",
        p_description: "22 CARTONS, 18 UNITS/CARTON, 4 PCS/UNIT",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 396,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_CLEAR_6PK",
        p_price: 6.41,
        p_currency: "USD",
        p_description: "22 CARTONS, 12 UNITS/CARTON, 6 PCS/UNIT",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 264,
    },
    {
      item_upc: {
        marketplace_region_id: "",
        organization_id: "123456789",
        vendor_id: "963852",
        upc: "",
        secondary_identifier: "",
        p_sku: "",
        p_title: "1 LP_WALL_DISPLAY_CLEAR_12PK",
        p_price: 12.82,
        p_currency: "USD",
        p_description: "57 CARTONS, 6 UNITS/CARTON, 12 PCS/UNIT",
        p_attributes: "",
        p_images: "",
        p_category: "",
        p_type: "",
        p_link: "",
        state: "",
        itemSource: "",
      },
      qty: 342,
    },
  ],
  total_price: 61384.56,
};
